<?php

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/request.php';

/**
 * Rebecca panel adapter.
 *
 * Rebecca requires every user to belong to one service. A service can expose
 * every protocol configured on its hosts, so the bot stores one service id as
 * the panel/product protocol selection and returns every link generated by it.
 */

function rebeccaNormalizeUrl($url)
{
    $url = trim((string) $url);
    $url = preg_replace('#/(dashboard|api)/?$#i', '', rtrim($url, '/'));
    return rtrim((string) $url, '/');
}

function rebeccaPanel($panelOrName)
{
    if (is_array($panelOrName)) {
        return $panelOrName;
    }
    return select('marzban_panel', '*', 'name_panel', $panelOrName, 'select');
}

function rebeccaErrorMessage($response, $decoded = null)
{
    if (!empty($response['error'])) {
        return (string) $response['error'];
    }
    if (!is_array($decoded)) {
        $decoded = json_decode((string) ($response['body'] ?? ''), true);
    }
    if (is_array($decoded)) {
        foreach (['detail', 'message', 'error', 'msg'] as $key) {
            if (!array_key_exists($key, $decoded) || $decoded[$key] === '') {
                continue;
            }
            return is_scalar($decoded[$key])
                ? (string) $decoded[$key]
                : json_encode($decoded[$key], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }
    }
    $status = (int) ($response['status'] ?? 0);
    return $status > 0 ? 'Rebecca API error (' . $status . ')' : 'Connection to Rebecca failed';
}

function rebeccaTokenPanel($panelOrCode, $verify = true)
{
    $panel = is_array($panelOrCode)
        ? $panelOrCode
        : select('marzban_panel', '*', 'code_panel', $panelOrCode, 'select');
    if (!$panel || !is_array($panel)) {
        return ['ok' => false, 'msg' => 'پنل ربکا پیدا نشد.'];
    }

    if ($verify && !empty($panel['datelogin'])) {
        $cached = json_decode($panel['datelogin'], true);
        $cachedAt = isset($cached['time']) ? strtotime($cached['time']) : false;
        if (!empty($cached['access_token']) && $cachedAt && (time() - $cachedAt) < 2700) {
            return ['ok' => true, 'access_token' => $cached['access_token']];
        }
    }

    $url = rebeccaNormalizeUrl($panel['url_panel'] ?? '') . '/api/admin/token';
    $request = new CurlRequest($url);
    $request->setHeaders([
        'Accept: application/json',
        'Content-Type: application/x-www-form-urlencoded',
    ]);
    $response = $request->post([
        'username' => (string) ($panel['username_panel'] ?? ''),
        'password' => (string) ($panel['password_panel'] ?? ''),
    ]);
    $body = json_decode((string) ($response['body'] ?? ''), true);
    if ((int) ($response['status'] ?? 0) < 200 || (int) ($response['status'] ?? 0) >= 300 || empty($body['access_token'])) {
        return [
            'ok' => false,
            'status' => (int) ($response['status'] ?? 0),
            'msg' => rebeccaErrorMessage($response, $body),
        ];
    }

    $cache = json_encode([
        'time' => date('Y-m-d H:i:s'),
        'access_token' => $body['access_token'],
    ], JSON_UNESCAPED_SLASHES);
    if (!empty($panel['code_panel'])) {
        update('marzban_panel', 'datelogin', $cache, 'code_panel', $panel['code_panel']);
    }
    return ['ok' => true, 'access_token' => $body['access_token']];
}

function rebeccaRequest($panelOrName, $method, $path, $payload = null, $retry = true)
{
    $panel = rebeccaPanel($panelOrName);
    if (!$panel || !is_array($panel)) {
        return ['ok' => false, 'status' => 0, 'msg' => 'پنل ربکا پیدا نشد.', 'data' => []];
    }
    $token = rebeccaTokenPanel($panel, $retry);
    if (!$token['ok']) {
        return ['ok' => false, 'status' => $token['status'] ?? 0, 'msg' => $token['msg'], 'data' => []];
    }

    $request = new CurlRequest(rebeccaNormalizeUrl($panel['url_panel']) . '/' . ltrim($path, '/'));
    $request->setHeaders(['Accept: application/json', 'Content-Type: application/json']);
    $request->setBearerToken($token['access_token']);
    $method = strtolower((string) $method);
    if ($method === 'get') {
        $response = $request->get();
    } elseif ($method === 'post') {
        $response = $request->post($payload === null ? '{}' : json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    } elseif ($method === 'put') {
        $response = $request->put($payload === null ? '{}' : json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    } elseif ($method === 'delete') {
        $response = $request->delete($payload === null ? null : json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    } else {
        return ['ok' => false, 'status' => 0, 'msg' => 'Unsupported Rebecca request method', 'data' => []];
    }

    $status = (int) ($response['status'] ?? 0);
    $body = json_decode((string) ($response['body'] ?? ''), true);
    if ($status === 401 && $retry) {
        if (!empty($panel['code_panel'])) {
            update('marzban_panel', 'datelogin', null, 'code_panel', $panel['code_panel']);
        }
        return rebeccaRequest($panel, $method, $path, $payload, false);
    }
    if ($status < 200 || $status >= 300) {
        return ['ok' => false, 'status' => $status, 'msg' => rebeccaErrorMessage($response, $body), 'data' => $body ?: []];
    }
    return ['ok' => true, 'status' => $status, 'msg' => '', 'data' => is_array($body) ? $body : []];
}

function rebeccaCheckConnection($panelOrName)
{
    return rebeccaRequest($panelOrName, 'get', '/api/system');
}

function rebeccaUsersSummary($panelOrName)
{
    $all = rebeccaRequest($panelOrName, 'get', '/api/users?offset=0&limit=1');
    if (!$all['ok']) {
        return $all;
    }
    $active = rebeccaRequest($panelOrName, 'get', '/api/users?offset=0&limit=1&status=active');
    return [
        'ok' => true,
        'status' => $all['status'],
        'msg' => '',
        'total' => (int) ($all['data']['total'] ?? 0),
        'active' => $active['ok'] ? (int) ($active['data']['total'] ?? 0) : null,
    ];
}

function rebeccaListUsers($panelOrName, $status = '', $offset = 0, $limit = 1000)
{
    $query = http_build_query([
        'offset' => max(0, (int) $offset),
        'limit' => max(1, min(1000, (int) $limit)),
        'status' => trim((string) $status),
    ]);
    $response = rebeccaRequest($panelOrName, 'get', '/api/users?' . $query);
    if (!$response['ok']) {
        return $response + ['items' => [], 'total' => 0];
    }
    return [
        'ok' => true,
        'status' => $response['status'],
        'msg' => '',
        'items' => is_array($response['data']['users'] ?? null) ? $response['data']['users'] : [],
        'total' => (int) ($response['data']['total'] ?? 0),
    ];
}

function rebeccaGetServices($panelOrName)
{
    $response = rebeccaRequest($panelOrName, 'get', '/api/v2/services?offset=0&limit=1000');
    if (!$response['ok']) {
        return $response + ['items' => []];
    }
    $items = $response['data']['services'] ?? $response['data']['items'] ?? $response['data'];
    $items = is_array($items) ? array_values(array_filter($items, function ($item) {
        return is_array($item) && (int) ($item['id'] ?? 0) > 0;
    })) : [];
    return ['ok' => true, 'status' => $response['status'], 'msg' => '', 'items' => $items];
}

function rebeccaGetService($panelOrName, $serviceId)
{
    return rebeccaRequest($panelOrName, 'get', '/api/v2/services/' . (int) $serviceId);
}

function rebeccaNormalizeServiceId($value)
{
    if (is_string($value)) {
        $decoded = json_decode($value, true);
        if (json_last_error() === JSON_ERROR_NONE) {
            $value = $decoded;
        }
    }
    if (is_array($value)) {
        if (isset($value['service_id'])) {
            return max(0, (int) $value['service_id']);
        }
        $value = reset($value);
    }
    return max(0, (int) $value);
}

function rebeccaResolveServiceId($panel, $product = null)
{
    if (is_array($product)) {
        $serviceId = rebeccaNormalizeServiceId($product['inbounds'] ?? null);
        if ($serviceId > 0) {
            return $serviceId;
        }
    }
    foreach (['proxies', 'inbounds', 'inboundid'] as $field) {
        $serviceId = rebeccaNormalizeServiceId($panel[$field] ?? null);
        if ($serviceId > 0) {
            return $serviceId;
        }
    }
    return 0;
}

function rebeccaAbsoluteUrl($panel, $url)
{
    $url = trim((string) $url);
    if ($url === '') {
        return '';
    }
    if (preg_match('#^https?://#i', $url)) {
        return $url;
    }
    return rebeccaNormalizeUrl($panel['url_panel'] ?? '') . '/' . ltrim($url, '/');
}

function rebeccaGetSubscriptionLinks($panel, array $user)
{
    $links = $user['links'] ?? [];
    if (is_string($links)) {
        $links = preg_split('/\r?\n/', trim($links));
    }
    $links = is_array($links) ? array_values(array_filter(array_map('trim', $links), 'strlen')) : [];
    if (!$links && !empty($user['subscription_url']) && function_exists('outputlink')) {
        $content = outputlink(rebeccaAbsoluteUrl($panel, $user['subscription_url']));
        if (is_string($content) && $content !== '') {
            if (function_exists('isBase64') && isBase64($content)) {
                $decoded = base64_decode($content, true);
                if ($decoded !== false) {
                    $content = $decoded;
                }
            }
            $links = array_values(array_filter(preg_split('/\r?\n/', trim($content)), 'strlen'));
        }
    }
    return $links;
}

function rebeccaCreateUser($panel, $product, $username, $expire, $dataLimit, $note, $isTest = false)
{
    $serviceId = rebeccaResolveServiceId($panel, $product);
    if ($serviceId < 1) {
        return ['ok' => false, 'status' => 0, 'msg' => 'ابتدا سرویس پیش‌فرض پنل ربکا را از مدیریت پنل انتخاب کنید.', 'data' => []];
    }
    $resetStrategy = (string) ($product['data_limit_reset'] ?? 'no_reset');
    if (!in_array($resetStrategy, ['no_reset', 'day', 'week', 'month', 'year'], true)) {
        $resetStrategy = 'no_reset';
    }
    $payload = [
        'username' => (string) $username,
        'service_id' => $serviceId,
        'status' => 'active',
        'expire' => (int) $expire > 0 ? (int) $expire : null,
        'data_limit' => max(0, (int) $dataLimit),
        'data_limit_reset_strategy' => $resetStrategy,
        'note' => (string) $note,
    ];
    $useOnHold = $isTest
        ? (($panel['on_hold_test'] ?? '1') !== '0')
        : (($panel['conecton'] ?? 'offconecton') !== 'offconecton');
    if ($useOnHold && (int) $expire > time()) {
        $payload['status'] = 'on_hold';
        $payload['expire'] = null;
        $payload['on_hold_expire_duration'] = (int) $expire - time();
    }
    $response = rebeccaRequest($panel, 'post', '/api/user', $payload);
    if ($response['ok'] && empty($response['data']['subscription_url']) && empty($response['data']['links'])) {
        $fullUser = rebeccaGetUser($panel, $username);
        if ($fullUser['ok']) {
            $response['data'] = $fullUser['data'];
        }
    }
    return $response;
}

function rebeccaGetUser($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'get', '/api/user/' . rawurlencode((string) $username));
}

function rebeccaModifyUser($panelOrName, $username, array $payload)
{
    $allowed = [
        'status', 'service_id', 'expire', 'data_limit', 'data_limit_reset_strategy',
        'note', 'telegram_id', 'contact_number', 'on_hold_expire_duration',
        'on_hold_timeout', 'ip_limit', 'auto_delete_in_days', 'flow', 'credential_key',
    ];
    $payload = array_intersect_key($payload, array_flip($allowed));
    if (!$payload) {
        return ['ok' => false, 'status' => 0, 'msg' => 'اطلاعاتی برای ویرایش کاربر ارسال نشده است.', 'data' => []];
    }
    return rebeccaRequest($panelOrName, 'put', '/api/user/' . rawurlencode((string) $username), $payload);
}

function rebeccaDeleteUser($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'delete', '/api/user/' . rawurlencode((string) $username));
}

function rebeccaResetUserUsage($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'post', '/api/user/' . rawurlencode((string) $username) . '/reset', []);
}

function rebeccaRevokeSubscription($panelOrName, $username)
{
    return rebeccaRequest($panelOrName, 'post', '/api/user/' . rawurlencode((string) $username) . '/revoke_sub', []);
}

function rebeccaUserOutput($panel, array $user, $customSubscriptionUrl = null)
{
    $subscriptionUrl = rebeccaAbsoluteUrl($panel, $user['subscription_url'] ?? '');
    return [
        'status' => (string) ($user['status'] ?? 'active'),
        'username' => (string) ($user['username'] ?? ''),
        'data_limit' => (int) ($user['data_limit'] ?? 0),
        'expire' => isset($user['expire']) ? (int) $user['expire'] : 0,
        'online_at' => $user['online_at'] ?? null,
        'used_traffic' => (int) ($user['used_traffic'] ?? 0),
        'links' => rebeccaGetSubscriptionLinks($panel, $user),
        'subscription_url' => $customSubscriptionUrl ?: $subscriptionUrl,
        'panel_subscription_url' => $subscriptionUrl,
        'sub_updated_at' => $user['sub_updated_at'] ?? null,
        'sub_last_user_agent' => $user['sub_last_user_agent'] ?? null,
        'uuid' => $user['proxies'] ?? $user['credential_key'] ?? null,
        'data_limit_reset' => $user['data_limit_reset_strategy'] ?? 'no_reset',
        'service_id' => isset($user['service_id']) ? (int) $user['service_id'] : null,
        'service_name' => $user['service_name'] ?? null,
    ];
}

function rebeccaServicesKeyboardData($panel, $selectedServiceId, $callbackPrefix, $title)
{
    $services = rebeccaGetServices($panel);
    if (!$services['ok']) {
        return ['ok' => false, 'msg' => $services['msg'], 'text' => '', 'keyboard' => null];
    }
    if (!$services['items']) {
        return ['ok' => false, 'msg' => 'هیچ سرویسی در پنل ربکا ساخته نشده است.', 'text' => '', 'keyboard' => null];
    }
    $selectedServiceId = (int) $selectedServiceId;
    $rows = [];
    foreach ($services['items'] as $service) {
        $id = (int) $service['id'];
        $name = trim((string) ($service['name'] ?? ('Service ' . $id)));
        if (function_exists('mb_strlen') && mb_strlen($name, 'UTF-8') > 48) {
            $name = mb_substr($name, 0, 45, 'UTF-8') . '...';
        }
        $rows[] = [[
            'text' => ($id === $selectedServiceId ? '✅ ' : '') . $name,
            'callback_data' => $callbackPrefix . $id,
        ]];
    }
    $rows[] = [[
        'text' => 'بازگشت به مدیریت',
        'callback_data' => 'admin',
    ]];
    return [
        'ok' => true,
        'msg' => '',
        'text' => "🧩 <b>{$title}</b>\n\nهر سرویس تمام پروتکل‌های فعال روی میزبان‌های خودش را به کاربر تحویل می‌دهد. سرویس موردنظر را انتخاب کنید:",
        'keyboard' => json_encode(['inline_keyboard' => $rows], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
    ];
}

function rebeccaServiceProtocols($panel, $serviceId)
{
    if ((int) $serviceId < 1) {
        return [];
    }
    $response = rebeccaGetService($panel, $serviceId);
    if (!$response['ok']) {
        return [];
    }
    $protocols = [];
    foreach (($response['data']['hosts'] ?? []) as $host) {
        $protocol = strtolower(trim((string) ($host['inbound_protocol'] ?? '')));
        if ($protocol !== '') {
            $protocols[] = $protocol;
        }
    }
    return array_values(array_unique($protocols));
}

